### ISSUE TITLE
Installation/Usage details in the Readme

### ISSUE THREAD

**Issue by jgandt** [tommcdo/vim-fubitive#10]
Could you please provide some brief installation and usage instructions in the Readme?

I installed the plugin with Vundle, but the plugin does not seem to work. However, I'm not sure exactly what to expect for how it works. I expect that it just works magically based on the git origin (as specified in the vim-fugitive plugin docs).

However, I can't be sure as to the expected behavior.

Even a few words as to expected behavior would be awesome.

I will try to dive into the code, but vimscript is not my forte.

Thanks for all the work you've done already!

**Comment by vlcinsky** [comment]
+1. As Bitbucket user, I am looking forward to use :Gbrowse and see my source on Bitbucket.

Regarding expected behaviour: I expect just that: when working on repository, which as origin pointing to Bitbucket, using `:Gbrowse` would open the project (or file) in the browser as Fugitive does with github based projects. Nothing more.

Anyway, I failed to install the plugin, using neovim and installing via `plug` plugin (which works great for all my other stuff).
Checking variable `:echo g:fugitive_browse_handlers` shows:

    [function('SNR>50_github_url'), function('<SNR>50_instaweb_url')]

No note about bitbucket stuff here.

**Comment by vlcinsky** [comment]
I can confirm, that with vim 7.4 this plugin works.

Installed via Plug.

With latest neovim --verion:

    NVIM 0.2.0-dev
    Build type: RelWithDebInfo

I seem to have general problems with installing anything via Plug properly (and deo manager did not work either), so better test it on vim first.

Regarding functionality: it works great. Selecting few lines in my source (with repository being on bitbucket) and using `:Gbrowse` it fires up my web browser (firefox), shows that file with selected lines highlighted. Awesome.

**Comment by mark2185** [comment]
Both `README.md` and `doc/vim-fubitive.txt` have been updated since then. 

Please reopen if you think something's missing! :)
